import Head from 'next/head'
import Navbar from '../components/Navbar'
import Intro from '../components/Intro'
import About from '@/components/About'
import Projects from '@/components/Projects'
import Skills from '@/components/Skills'

export default function Home() {
  return (
    <>
      <Head>
        <title>Guruprasad Gaikwad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Intro />
      <About />
      <Skills />
      <Projects />
    </>
  )

}
